DO $$
DECLARE set_id uuid; song_id uuid; sess_id uuid;
BEGIN
  SELECT id INTO sess_id FROM cyc_sessions WHERE session_num=4;
  INSERT INTO cyc_sets (session_id,set_index,label) VALUES (sess_id,3,'Set Jorge') RETURNING id INTO set_id;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,0,'Danny Elfman','The little things') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,1,'Depeche Mode','Policy of Truth') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,2,'Empire of the Sun','DNA') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,3,'Ex Cops','Black Soap') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,4,'Filter','Take a picture') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,5,'Gazebo','I like Chopin (Extended Dance Version)') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,6,'Iron Maiden','The Trooper') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,7,'Jean Michel Jarre','AERO') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,8,'Kiesza','Hideaway') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,9,'Lighthouse family','Raincloud') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,10,'Lost Prophets','Shinobi vs Dragon ninja') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,11,'Radiohead','Weird Fishes') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,12,'Re flex','The politics of dancing') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,13,'Robbie Williams','Feel') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,14,'Smashing Satellites','Waterfall') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,15,'Soda Stereo','En la ciudad de la furia') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,16,'Soda Stereo','Prófugos') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,17,'Soda Stereo','Lo que sangra (La cúpula)') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,18,'Soda Stereo','Te para tres (Unplugged)') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,19,'Sussie 4','Remote Control') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio R.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
END $$;