DO $$
DECLARE set_id uuid; song_id uuid; sess_id uuid;
BEGIN
  SELECT id INTO sess_id FROM cyc_sessions WHERE session_num=4;
  INSERT INTO cyc_sets (session_id,set_index,label) VALUES (sess_id,2,'Set Hernan') RETURNING id INTO set_id;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,0,'Angels & Agony','Monument') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,1,'Brandon Flowers','Digging up the heart') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,2,'Cheerleader','The sunshine of your youth') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,3,'Chemical Brothers','Go') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',4.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,4,'Daft Punk','Instant Crush') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,5,'David Bowie','Valentine''s day') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,6,'Future islands','A dream of you and me') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,7,'Gorillaz','On Melancholy Hill') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,8,'Imagine dragons','Shots') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,9,'Maroon 5','This summer') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',4.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',5.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,10,'Miami Horror','Stranger') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,11,'Miranda','Fantasmas') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,12,'Moby','Perfect Life') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,13,'OMD','Metroland') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,14,'One Republic','Counting stars') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,15,'Somos','Somos') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',4.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',4.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',4.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,16,'The Alan Parsons Project','Do you live at all?') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,17,'Tony Bennett & Lady Gaga','Cheek to cheek') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',4.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',4.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,18,'U2','California (there is no end to love)') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,19,'White Lies','Big Tv') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jose J',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Lucho',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
END $$;