DO $$
DECLARE set_id uuid; song_id uuid; sess_id uuid;
BEGIN
  SELECT id INTO sess_id FROM cyc_sessions WHERE session_num=12;
  INSERT INTO cyc_sets (session_id,set_index,label) VALUES (sess_id,1,'Set Giuse') RETURNING id INTO set_id;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,0,'Hilario Durand','Night in Tunisia') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,1,'Coldplay','Speed of sound') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,2,'Supertramp','My kind of lady') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,3,'Alan Parsons','I would not want to be like you') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,4,'Barbra Streisand','Someone I used to love') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,5,'Neil Diamond','September morning') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,6,'Lou Rawls','See you when I get there') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,7,'Toto','You''ll supply the night') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,8,'Fleetwood Mac','You make loving fun') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,9,'America','A horse with no name') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,10,'Nancy Sinatra','These boots are made for waking') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,11,'Elthon Jhon','Friends') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,12,'Jose Feliciano','Light my fire') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,13,'Queen','Love of my life') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,14,'Cat Stevens','Moonshadow') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,15,'Charly Garcia','No bombardeen Buenos Aires') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Patrick',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Juan Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
END $$;