DO $$
DECLARE set_id uuid; song_id uuid; sess_id uuid;
BEGIN
  SELECT id INTO sess_id FROM cyc_sessions WHERE session_num=11;
  INSERT INTO cyc_sets (session_id,set_index,label) VALUES (sess_id,4,'Set Mauricio') RETURNING id INTO set_id;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,0,'Men Without Hats','I Got The Message') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,1,'The Doobie Brothers','Listen to Music') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,2,'Blur','Coffee & TV') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,3,'Joy Again','Looking Out for You') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,4,'Toto','Georgy Porgy') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,5,'Los Prisioneros','Maldito Sudaca') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,6,'The Weeknd','Save Your Tears') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,7,'Luis Alberto Spinetta, Charly García','Rezo por Vos') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,8,'Turf','Pasos Al Costado') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,9,'Natalia Lafourcade','Hasta la Raiz') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,10,'Mumford & Sons','I Will Wait') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,11,'Evanescence','My Immortal') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,12,'Travelling Wildburys','Handle With Care') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,13,'Morrisey','The Last of the Famous International Playboys') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,14,'Bee Gees','Alone') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,15,'Daryl Hall & John Oates','out of touch') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,16,'Cafuné','Tek It') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,17,'The Stone Roses','I Wanna Be Adored') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,18,'Fitz and The Tantrums','Out of My League') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,19,'Robert Palmer','Addicted To Love') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Francisco',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mario',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Jorge A.',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Julio',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
END $$;