DO $$
DECLARE set_id uuid; song_id uuid; sess_id uuid;
BEGIN
  SELECT id INTO sess_id FROM cyc_sessions WHERE session_num=4;
  INSERT INTO cyc_sets (session_id,set_index,label) VALUES (sess_id,5,'Set Rafael') RETURNING id INTO set_id;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,0,'Bruce Springsteen','I´m on fire') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,1,'Deep Purple','Child In Time') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,2,'Deff lepard','Pour some sugar on me') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,3,'Dire Straits','Brother in arms') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',10.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,4,'Echosmith','Cool Kids') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,5,'Ed Sheeram','I´m a Mess') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,6,'El último de la fila','Insurrección') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,7,'Elton John & Pavarotti','Live Like Horses - 1997') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,8,'INXS','Nevet Tear Us Apart') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,9,'Joan Osborne & Pavarotti','St. Teresa') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',5.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,10,'Nico & Vinz','Am I Wrong') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,11,'Omi (Felix Jaehn Remix)','Cheerleader') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,12,'Pearl Jam','Even Flow') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,13,'Shocking Blue','Never Marry a Railroad') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,14,'The Alan Parsons Project','Games People Play') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,15,'The Beatles','Eleanor Rigby') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,16,'The Rolling Stones','Doom and Gllom 12') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,17,'The Weeknd','Earned It') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',6.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',6.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,18,'Toto','Hold the line') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',9.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_songs (set_id,song_index,artist,title) VALUES (set_id,19,'Tracy Chapman','Telling Stores') RETURNING id INTO song_id;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Hernan',8.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Daniel',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Carlos',7.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Giusse',8.5) ON CONFLICT (song_id,voter_name) DO NOTHING;
  INSERT INTO cyc_votes (song_id,voter_name,score) VALUES (song_id,'Mauricio O.',7.0) ON CONFLICT (song_id,voter_name) DO NOTHING;
END $$;